name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: docker login --username shuhamknoldus --password $SUPER_SECRET; docker build . --file Dockerfile --tag shuhamknoldus/kafka-container:latest; docker push shuhamknoldus/kafka-container:latest;
        
